package org.publiccms.entities.cms;

import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

import static org.publiccms.common.database.CmsUpgrader.IDENTIFIER_GENERATOR;

/**
 * CmsAttractInvestment generated by hbm2java
 */
@Entity
@Table(name = "cms_attract_investment")
public class CmsAttractInvestment implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "姓名")
    private String username;
    @GeneratorColumn(title = "性别")
    private String sex;
    @GeneratorColumn(title = "电话")
    private String phone;
    @GeneratorColumn(title = "意向地区")
    private String place;
    @GeneratorColumn(title = "投资额度")
    private String amount;
    @GeneratorColumn(title = "留言内容")
    private String content;
    @GeneratorColumn(title = "是否有店铺")
    private String hasStore;
    @GeneratorColumn(title = "留言日期")
    private String createDate;

    public CmsAttractInvestment() {
    }

    public CmsAttractInvestment(String username, String sex,String content, String phone, String place, String amount, String hasStore,String createDate) {
        this.username = username;
        this.sex = sex;
        this.content = content;
        this.phone = phone;
        this.place = place;
        this.amount = amount;
        this.hasStore = hasStore;
        this.createDate = createDate;
    }

    

    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = IDENTIFIER_GENERATOR)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "username", nullable = false)
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "create_date", nullable = false)
	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

    @Column(name = "phone", nullable = false)
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    @Column(name = "place", nullable = false)
    public String getPlace() {
        return place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    @Column(name = "amount", nullable = false)
    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    @Column(name = "sex", nullable = false)
    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "has_store", nullable = false)
    public String getHasStore() {
        return hasStore;
    }

    public void setHasStore(String hasStore) {
        this.hasStore = hasStore;
    }
}
