package org.publiccms.entities.cms;

import static org.publiccms.common.database.CmsUpgrader.IDENTIFIER_GENERATOR;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * CmsCategory generated by hbm2java
 */
@Entity
@Table(name = "cms_map")
public class CmsMap implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "门店昵称")
    private String store_name;
    @GeneratorColumn(title = "联系方式")
    private String contact;
    @GeneratorColumn(title = "门店地址")
    private String address;
    @GeneratorColumn(title = "封面")
    private String cover;
    @GeneratorColumn(title = "经度")
    private String lng;
    @GeneratorColumn(title = "纬度")
    private String lat;
    @GeneratorColumn(title = "url")
    private String url;

    public CmsMap() {
    }

    public CmsMap( String store_name, String contact,String address,String cover,String lng,String lat,String url) {
        this.store_name = store_name;
        this.contact = contact;
        this.address = address;
        this.cover = cover;
        this.lng = lng;
        this.lat = lat;
        this.url=url;
    }

    

    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = IDENTIFIER_GENERATOR)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "store_name", nullable = false)
    public String getStore_name() {
        return store_name;
    }

    public void setStore_name(String store_name) {
        this.store_name = store_name;
    }

    @Column(name = "contact", nullable = false)
    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    @Column(name = "address", nullable = false)
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "cover", nullable = false)
    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    @Column(name = "lng", nullable = false)
    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    @Column(name = "lat", nullable = false)
    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    @Column(name = "url", nullable = false)
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

    

}
